export const projectsData = [
  {
    id: 1,
    title: "Bachelor's Thesis",
    description: "Computer Engineering Bachelor's Final Project",
    image: "/images/projects/tfg.jpeg",
    tag: ["All", "Cybersecurity", "Algorithms & Data Structures", "Documentation"],
    gitUrl: "https://github.com/aleexnager/stego-project",
    previewUrl: "https://github.com/aleexnager/stego-project",
    svgs: ["python"],
    modalText: "\'Análisis y optimización de algoritmos de esteganografía en imágenes basado en teoría de la información\' is the title of my Bachelor's Final Project. In this project I analyzed the LSB algorithm and optimized it using the entropy of the image, creating 2 new optimized algorithms.",
    modalButtonText: "Go to repository",
  },
  {
    id: 2,
    title: "Data compressor",
    description: "Motorola assembly language data compressor.",
    image: "/images/projects/dataCompressor.png",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "https://github.com/aleexnager/Proyecto-Ensamblador-M88110",
    previewUrl: "https://github.com/aleexnager/Proyecto-Ensamblador-M88110",
    svgs: ["asm"],
    modalText: "Fully functional data compressor built in Motorola assembly language. It was a project for the Computer Structure class at UPM.",
    modalButtonText: "Go to repository",
  },
  {
    id: 3,
    title: "Language compiler",
    description: "Full project building a language compiler for JS.",
    image: "/images/projects/languageCompiler.jpg",
    tag: ["All", "Algorithms & Data Structures", "Other"],
    gitUrl: "https://github.com/aleexnager/PdL",
    previewUrl: "https://github.com/aleexnager/PdL",
    svgs: ["c"],
    modalText: "Complemete language compiler built in C. During this project I learned how instructions are interpreted by computers. It was a project for the Languages Processors class at UPM.",
    modalButtonText: "Go to repository",
  },
  {
    id: 4,
    title: "A* search algorithm",
    description: "Lyon metro system with shortest path search.",
    image: "/images/projects/aStarAlgorythm.png",
    tag: ["All", "IA & Machine Learning", "Algorithms & Data Structures", "Other"],
    gitUrl: "https://github.com/aleexnager/IA",
    previewUrl: "https://github.com/aleexnager/IA",
    svgs: ["python"],
    modalText: "A* search algorithm implementation in Python. Using Lyon metro system as a case study, the algorithm finds the shortest path between two stations.",
    modalButtonText: "Go to repository",
  },
  {
    id: 5,
    title: "Minishell",
    description: "Creation a fully functional UNIX Bash shell.",
    image: "/images/projects/minishell.PNG",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: ["c"],
    modalText: "Minishell is a project that I did for the Operating Systems class at UPM. It is a fully functional UNIX Bash shell built in C. Unfortunately, I cannot share the code because this project because DATSI UPM does not allow it. However, you can contact me for more information and i'll be happy to show anything you may be interested in.",
    modalButtonText: "",
  },
  {
    id: 6,
    title: "Input/Output via interruptions",
    description: "Motorola assembly language project.",
    image: "/images/projects/E-S-controller.jpg",
    tag: ["All", "Architecture"],
    gitUrl: "https://github.com/aleexnager/E-S-mediante-interrupciones",
    previewUrl: "https://github.com/aleexnager/E-S-mediante-interrupciones",
    svgs: ["asm"],
    modalText: "Assembly language project for the Computer Arquiteture class at UPM. It is a project that simulates an input/output controller using interruptions.",
    modalButtonText: "Go to repository",
  },
  {
    id: 7,
    title: "This Web Portfolio",
    description: "The website you are currently on and its source code.",
    image: "/images/projects/thisWebPortfolio.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/anager",
    previewUrl: "/",
    svgs: ["javascript", "next", "tailwind",],
    modalText: "This is my current web portfolio, the website you are currently on. I built it using Next.js, Tailwind CSS, . I am very proud of this project because I learned a lot from it.",
    modalButtonText: "Go Home",
  },
  {
    id: 8,
    title: "Threads racecourse",
    description: "Small game with threads and semaphores.",
    image: "/images/projects/racecourse.png",
    tag: ["All", "Algorithms & Data Structures", "Games"],
    gitUrl: "https://github.com/aleexnager/Hipodromo",
    previewUrl: "https://github.com/aleexnager/Hipodromo",
    svgs: ["c"],
    modalText: "Super simple game that simulates a racecourse using threads and semaphores.",
    modalButtonText: "Go to repository",
  },
  {
    id: 9,
    title: "Tennis tournament",
    description: "Web app to create and manage tennis tournaments.",
    image: "/images/projects/tennisTournament.jpg",
    tag: ["All", "Web", "API & Web Service"],
    gitUrl: "https://github.com/aleexnager/tennis-tournament",
    previewUrl: "https://tennis-tournament-alpha.vercel.app",
    svgs: ["typescript", "next", "tailwind", "mongodb"],
    modalText: "Web app that allows you to create and manage tennis tournaments. This was a project for my Software Engineering class at UPM.",
    modalButtonText: "Go to repository",
  },
  {
    id: 10,
    title: "Old Web Portfolio",
    description: "Simple personal web portfolio, my old website.",
    image: "/images/projects/oldWebPortfolio.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/web-portfolio",
    previewUrl: "https://alex-nager-portfolio.onrender.com",
    svgs: ["html", "css", "javascript",],
    modalText: "This is my old web portfolio, my first simple personal website that I built using HTML, CSS, and JavaScript. It was my first web project and I learned a lot from it. Just be aware that some of its functionalities are not currently working as it is no longer being maintained.",
    modalButtonText: "View website",
  },
];