export const projectsData = [
  {
    id: 1,
    title: "Web Portfolio",
    description: "Simple personal web portfolio, my old website.",
    image: "/images/projects/project1.jpg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/web-portfolio",
    previewUrl: "/",
    svgs: ["html", "css", "javascript",],
  },
  {
    id: 2,
    title: "Data compressor",
    description: "Motorola assembly language data compressor.",
    image: "/images/projects/project2.jpg",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "https://github.com/aleexnager/Proyecto-Ensamblador-M88110",
    previewUrl: "/",
    svgs: ["emacs"],
  },
  {
    id: 3,
    title: "Language compiler",
    description: "Full project buildind a language compiler.",
    image: "/images/projects/project3.jpg",
    tag: ["All", "Algorithms & Data Structures", "Other"],
    gitUrl: "https://github.com/aleexnager/PdL",
    previewUrl: "/",
    svgs: ["c"],
  },
  {
    id: 4,
    title: "A* search algorithm",
    description: "Lyon metro system with shortest path search.",
    image: "/images/projects/project4.jpg",
    tag: ["All", "IA & Machine Learning", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: ["python"],
  },
  {
    id: 5,
    title: "Minishell",
    description: "Creation a fully functional UNIX Bash shell.",
    image: "/images/projects/project5.jpg",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: ["c"],
  },
  {
    id: 6,
    title: "This Web Portfolio",
    description: "The website you are currently on and its source code.",
    image: "/images/projects/project6.jpg",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/anager",
    previewUrl: "/",
    svgs: ["javascript", "nextjs", "tailwind",],
  },
  /*{
    id: 7,
    title: "Project 7",
    description: "This is project 7",
    image: "/images/projects/project6.jpg",
    tag: ["All", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: [
    ],
  },
  {
    id: 8,
    title: "Project 8",
    description: "This is project 8",
    image: "/images/projects/project6.jpg",
    tag: ["All", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: [
    ],
  },*/
];