export const projectsData = [
  {
    id: 1,
    title: "Old Web Portfolio",
    description: "Simple personal web portfolio, my old website.",
    image: "/images/projects/oldWebPortfolio.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/web-portfolio",
    previewUrl: "https://alex-nager-portfolio.onrender.com",
    svgs: ["html", "css", "javascript",],
  },
  {
    id: 2,
    title: "Data compressor",
    description: "Motorola assembly language data compressor.",
    image: "/images/projects/dataCompressor.png",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "https://github.com/aleexnager/Proyecto-Ensamblador-M88110",
    previewUrl: "https://github.com/aleexnager/Proyecto-Ensamblador-M88110",
    svgs: ["asm"],
  },
  {
    id: 3,
    title: "Language compiler",
    description: "Full project buildind a language compiler for JS.",
    image: "/images/projects/languageCompiler.jpg",
    tag: ["All", "Algorithms & Data Structures", "Other"],
    gitUrl: "https://github.com/aleexnager/PdL",
    previewUrl: "https://github.com/aleexnager/PdL",
    svgs: ["c"],
  },
  {
    id: 4,
    title: "A* search algorithm",
    description: "Lyon metro system with shortest path search.",
    image: "/images/projects/aStarAlgorythm.png",
    tag: ["All", "IA & Machine Learning", "Other"],
    gitUrl: "https://github.com/aleexnager/IA",
    previewUrl: "https://github.com/aleexnager/IA",
    svgs: ["python"],
  },
  {
    id: 5,
    title: "Minishell",
    description: "Creation a fully functional UNIX Bash shell.",
    image: "/images/projects/minishell.PNG",
    tag: ["All", "Architecture", "Other"],
    gitUrl: "/",
    previewUrl: "/",
    svgs: ["c"],
  },
  {
    id: 6,
    title: "This Web Portfolio",
    description: "The website you are currently on and its source code.",
    image: "/images/projects/thisWebPortfolio.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/aleexnager/anager",
    previewUrl: "/",
    svgs: ["javascript", "next", "tailwind",],
  },
  {
    id: 7,
    title: "Input/Output via interruptions",
    description: "Motorola assembly language project.",
    image: "/images/projects/E-S-controller.jpg",
    tag: ["All", "Architecture"],
    gitUrl: "https://github.com/aleexnager/E-S-mediante-interrupciones",
    previewUrl: "https://github.com/aleexnager/E-S-mediante-interrupciones",
    svgs: ["asm"],
  },
  {
    id: 8,
    title: "Threads racecourse",
    description: "Small game with threads and semaphores.",
    image: "/images/projects/racecourse.png",
    tag: ["All", "Algorithms & Data Structures", "Games"],
    gitUrl: "https://github.com/aleexnager/Hipodromo",
    previewUrl: "https://github.com/aleexnager/Hipodromo",
    svgs: ["c"],
  },
];