export const projectsData = [
  {
    id: 1,
    title: "Project 1",
    description: "This is project 1",
    image: "/images/projects/project1.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 2,
    title: "Project 2",
    description: "This is project 2",
    image: "/images/projects/project2.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 3,
    title: "Project 3",
    description: "This is project 3",
    image: "/images/projects/project3.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 4,
    title: "Project 4",
    description: "This is project 4",
    image: "/images/projects/project4.jpg",
    tag: ["All", "Other"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 5,
    title: "Project 5",
    description: "This is project 5",
    image: "/images/projects/project5.jpg",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
  },
  {
    id: 6,
    title: "Project 6",
    description: "This is project 6",
    image: "/images/projects/project3.jpg",
    tag: ["All", "Other"],
    gitUrl: "/",
    previewUrl: "/",
  },
];